INFO:root:----------------------------------------
INFO:root:Server loaded
INFO:root:200 POST /ws/usage/new (127.0.0.1) 1.16ms
INFO:root:----------------------------------------
INFO:root:Server loaded
INFO:root:new usage
INFO:root:{'_id': ObjectId('52ebdbb2848b0c7d9db52cdf'),
 u'date': datetime.datetime(2014, 1, 31, 17, 21, 54, 665000, tzinfo=<bson.tz_util.FixedOffset object at 0x7f0c2f077950>),
 u'duration': u'666',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
INFO:root:200 POST /ws/usage/new (127.0.0.1) 1.31ms
INFO:root:----------------------------------------
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 18:27:51.026754
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 18:38:04.350252
INFO:root:new usage
INFO:root:{'_id': ObjectId('52ebdf81848b0c7e174d2e34'),
 u'date': datetime.datetime(2014, 1, 31, 17, 38, 9, 906000, tzinfo=<bson.tz_util.FixedOffset object at 0x7f47fe8949d0>),
 u'duration': u'666',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
INFO:root:200 POST /ws/usage (127.0.0.1) 1.29ms
ERROR:root:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', body='', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0', 'Connection': 'keep-alive', 'Cookie': 'PVELangCookie=fr; org.cups.sid=eb4c977f82cc5561dd1a1a446691198d', 'Test': 'test'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1042, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "./server.py", line 48, in get
    self.write(json.dump(usage.find()))
TypeError: dump() takes at least 2 arguments (1 given)
ERROR:root:500 GET /ws/usage (127.0.0.1) 0.89ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.20ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.15ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 18:39:40.368732
INFO:root:new usage
INFO:root:{'_id': ObjectId('52ebdfdf848b0c7ea8969b40'),
 u'date': datetime.datetime(2014, 1, 31, 17, 39, 43, 937000, tzinfo=<bson.tz_util.FixedOffset object at 0x7fdbf2ef19d0>),
 u'duration': u'666',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
INFO:root:200 POST /ws/usage (127.0.0.1) 1.27ms
ERROR:root:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', body='', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0', 'Connection': 'keep-alive', 'Cookie': 'PVELangCookie=fr; org.cups.sid=eb4c977f82cc5561dd1a1a446691198d', 'Cache-Control': 'max-age=0', 'Test': 'test'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1042, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "./server.py", line 48, in get
    self.write(json.dumps(usage.find()))
  File "/usr/lib/python2.7/json/__init__.py", line 233, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 203, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 266, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <pymongo.cursor.Cursor object at 0x7fdbf2a65fd0> is not JSON serializable
ERROR:root:500 GET /ws/usage (127.0.0.1) 1.26ms
ERROR:root:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', body='', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0', 'Connection': 'keep-alive', 'Cookie': 'PVELangCookie=fr; org.cups.sid=eb4c977f82cc5561dd1a1a446691198d', 'Test': 'test'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1042, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "./server.py", line 48, in get
    self.write(json.dumps(usage.find()))
  File "/usr/lib/python2.7/json/__init__.py", line 233, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 203, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 266, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <pymongo.cursor.Cursor object at 0x7fdbf2a720d0> is not JSON serializable
ERROR:root:500 GET /ws/usage (127.0.0.1) 0.50ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 21:44:42.627200
WARNING:tornado.access:404 POST /ws/usage (127.0.0.1) 0.56ms
ERROR:tornado.application:Uncaught exception POST /ws/usage/ (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='POST', uri='/ws/usage/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '547', 'Accept': 'text/plain', 'Accept-Encoding': 'identity'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: post() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 POST /ws/usage/ (127.0.0.1) 27.41ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:09:12.442747
ERROR:tornado.application:Uncaught exception POST /ws/usage/ (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='POST', uri='/ws/usage/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '547', 'Accept': 'text/plain', 'Accept-Encoding': 'identity'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: post() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 POST /ws/usage/ (127.0.0.1) 1.49ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:10:39.154639
ERROR:tornado.application:Uncaught exception POST /ws/usage/ (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='POST', uri='/ws/usage/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '547', 'Accept': 'text/plain', 'Accept-Encoding': 'identity'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: post() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 POST /ws/usage/ (127.0.0.1) 1.47ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:11:09.103175
WARNING:tornado.access:404 POST /ws/usage/ (127.0.0.1) 0.56ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:16:39.936800
INFO:root:new usage
INFO:root:{'_id': ObjectId('52ec132670baa53214a91125'),
 u'date': datetime.datetime(2014, 1, 31, 21, 18, 30, 636000, tzinfo=<bson.tz_util.FixedOffset object at 0x1811950>),
 u'duration': u'00:45:24',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'./gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
INFO:tornado.access:200 POST /ws/usage (127.0.0.1) 149.48ms
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 48, in get
    self.write(json.dumps(usage.find()))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <pymongo.cursor.Cursor object at 0x18fedd0> is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 94.02ms
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 48, in get
    self.write(json.dumps(usage.find()))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <pymongo.cursor.Cursor object at 0x18fead0> is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 0.76ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:35:52.223442
INFO:root:new usage
INFO:root:{'_id': ObjectId('52ec173f70baa5375ccaa42a'),
 u'date': datetime.datetime(2014, 1, 31, 21, 35, 59, 607000, tzinfo=<bson.tz_util.FixedOffset object at 0xfb1910>),
 u'duration': u'00:45:24',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'./gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
INFO:tornado.access:200 POST /ws/usage (127.0.0.1) 1.93ms
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 48, in get
    self.write(json.dumps(usage.find(), default=json_util.default))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 220, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: <pymongo.cursor.Cursor object at 0x109ed90> is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 1.77ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:42:28.821677
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 49, in get
    self.write(json.dumps(usage.find(), default=json_util.default))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 220, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: <pymongo.cursor.Cursor object at 0x7fe4a437b650> is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 2.15ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 22:47:37.347643
INFO:tornado.access:200 GET /ws/usage (127.0.0.1) 1.09ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:02:58.442777
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"312f6118ead715482b065d4f1ad9625912171fac"', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 48, in get
    usage_list = usage.find().sort({'date':-1}).limit(1)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 581, in sort
    keys = helpers._index_list(key_or_list, direction)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 42, in _index_list
    raise TypeError("if no direction is specified, "
TypeError: if no direction is specified, key_or_list must be an instance of list
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 1.93ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:08:14.099880
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:09:04.377762
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 48, in get
    usage_list = usage.find().sort(('date',-1)).limit(1)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 581, in sort
    keys = helpers._index_list(key_or_list, direction)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 42, in _index_list
    raise TypeError("if no direction is specified, "
TypeError: if no direction is specified, key_or_list must be an instance of list
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 2.63ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:12:33.118806
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 49, in get
    self.write(json.dumps(usage_list), default=json_util.default)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <pymongo.cursor.Cursor object at 0x7f058d8e0610> is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 1.95ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:23:53.039588
INFO:root:{u'_id': ObjectId('52ec173f70baa5375ccaa42a'),
 u'date': datetime.datetime(2014, 1, 31, 21, 35, 59, 607000),
 u'duration': u'00:45:24',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'./gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
INFO:tornado.access:200 GET /ws/usage (127.0.0.1) 1.85ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:26:37.898112
INFO:root:{u'_id': ObjectId('52ec173f70baa5375ccaa42a'),
 u'date': datetime.datetime(2014, 1, 31, 21, 35, 59, 607000),
 u'duration': u'00:45:24',
 u'logType': u'3Dprinter',
 u'material quantity': u'0.3cm3',
 u'object': {u'extrusion_width_ratio': u'0',
             u'filament used': u'5.0mm',
             u'filament_diameter': u'2.92',
             u'file': u'./gcode_example.gcode',
             u'fill_density': u'0.3',
             u'gcode-generation': u'generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59',
             u'infill_speed': u'30',
             u'layer_height': u'0.40',
             u'nozzle_diameter': u'0.5',
             u'perimeter_speed': u'30',
             u'perimeters': u'3',
             u'scale': u'1',
             u'solid_layers': u'3',
             u'travel_speed': u'100'},
 u'result': u'OK',
 u'tool': u'Test'}
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"da39a3ee5e6b4b0d3255bfef95601890afd80709"', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 51, in get
    self.write(json.dumps(item), default=json_util.default)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2014, 1, 31, 21, 35, 59, 607000) is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 3.16ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:28:50.808193
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "./server.py", line 49, in get
    self.write(json.dumps(usage_list, default=json_util.default))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 220, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: <pymongo.cursor.Cursor object at 0x7f200f95a610> is not JSON serializable
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 1.94ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:33:02.501043
INFO:tornado.access:200 GET /ws/usage (127.0.0.1) 1.24ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-01-31 23:33:27.356531
INFO:tornado.access:200 GET /ws/usage (127.0.0.1) 1.29ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-01 21:18:26.836893
WARNING:tornado.access:404 GET /static (127.0.0.1) 0.54ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.34ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.37ms
WARNING:tornado.general:403 GET /static/img/ (127.0.0.1): img/ is not a file
WARNING:tornado.access:403 GET /static/img/ (127.0.0.1) 0.91ms
INFO:tornado.access:200 GET /static/img/loading.gif (127.0.0.1) 45.90ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-01 21:34:58.340256
INFO:tornado.access:200 GET /static/test.html (127.0.0.1) 3.82ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:41:06.439975
INFO:tornado.access:200 GET /ws/usage (127.0.0.1) 18.86ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:42:26.176836
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"7af15e14e54a4fbf9f6da4e91fdd59747891a61c"', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1179, in _execute_finish
    self.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 741, in finish
    self.set_etag_header()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1084, in set_etag_header
    etag = self.compute_etag()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1074, in compute_etag
    hasher.update(part)
TypeError: must be string or buffer, not None
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 3.59ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:43:01.683886
ERROR:tornado.application:Uncaught exception GET /ws/usage (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1179, in _execute_finish
    self.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 741, in finish
    self.set_etag_header()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1084, in set_etag_header
    etag = self.compute_etag()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1074, in compute_etag
    hasher.update(part)
TypeError: must be string or buffer, not None
ERROR:tornado.access:500 GET /ws/usage (127.0.0.1) 3.04ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:44:04.194423
INFO:tornado.access:200 GET /ws/usage (127.0.0.1) 1.88ms
INFO:tornado.access:304 GET /ws/usage (127.0.0.1) 1.58ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.37ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.36ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:53:55.863336
WARNING:tornado.access:404 GET /ws/usage/52ec173f70baa5375ccaa42a (127.0.0.1) 0.50ms
WARNING:tornado.access:404 GET /ws/usage/52ec173f70baa5375ccaa42a (127.0.0.1) 0.39ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:55:28.936520
ERROR:tornado.application:Uncaught exception GET /ws/usage/52ec173f70baa5375ccaa42a (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage/52ec173f70baa5375ccaa42a', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: get() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 GET /ws/usage/52ec173f70baa5375ccaa42a (127.0.0.1) 1.66ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:56:34.058943
ERROR:tornado.application:Uncaught exception GET /ws/usage/52ec173f70baa5375ccaa42a (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage/52ec173f70baa5375ccaa42a', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: get() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 GET /ws/usage/52ec173f70baa5375ccaa42a (127.0.0.1) 1.43ms
WARNING:tornado.access:404 GET /ws/usage (127.0.0.1) 0.40ms
WARNING:tornado.access:404 GET /ws/usage (127.0.0.1) 0.40ms
WARNING:tornado.access:404 GET /ws/usage (127.0.0.1) 0.36ms
ERROR:tornado.application:Uncaught exception GET /ws/usage/ (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: get() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 GET /ws/usage/ (127.0.0.1) 0.67ms
INFO:root:----------------------------------------
INFO:root:Server loaded - 2014-02-03 10:57:44.441305
ERROR:tornado.application:Uncaught exception GET /ws/usage/ (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/ws/usage/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'null', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/json', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1153, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1174, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
TypeError: get() takes exactly 1 argument (2 given)
ERROR:tornado.access:500 GET /ws/usage/ (127.0.0.1) 1.61ms
